### ISSUE TITLE
批量检测时候报错

### ISSUE THREAD

**Issue by lupus721** [ysrc/F-Scrack#2]
只添加2个ip地址，然后就会报错

python F-Scrack.py -h 2.txt

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "F-Scrack.py", line 272, in run
    self.Sock.sendto(self.packet, (ip, 0))
gaierror: [Errno -2] Name or service not known

**Comment by ywolf** [comment]
把 2.txt 文件名改为 2.ini

**Comment by lupus721** [comment]
好吧，谢谢

还有就是，我想把所有的扫描结果都导出，不论成功失败，应该怎么做呢

**Comment by ywolf** [comment]
python F-Scrack.py -h 10.x.x.x >log.txt
